### ISSUE TITLE
Ctrl+A does nothing

### ISSUE THREAD

**Issue by SinyoMinyo** [timlau/yumex-ng#114]
**Describe the bug**
When i open Yum Extender on my Nobara, go in the Packages tab and press Ctrl+A nothing happens. But in the Shortcut menu it says "Ctrl+A Select All". In Firefox Ctrl+A works perfectly.

**Versions**
5.0.3 (DNF4)

**What Distro are you running?**
Nobara Linux 40
KDE Plasma Version: 6.2.3
KDE Frameworks Version: 6.8.0
Qt Version: 6.7.2
Kernel Version: 6.11.9-200.fsync.fc40.x86_64 (64-bit)

**Comment by SinyoMinyo** [comment]
**Logs**
In Terminal:
...@nobara-pc:~$ yumex -d

(process:6114): Gtk-WARNING **: 10:51:07.408: Unknown key gtk-modules in /home/stefanw/.config/gtk-4.0/settings.ini

(process:6114): Adwaita-WARNING **: 10:51:07.417: Using GtkSettings:gtk-application-prefer-dark-theme with libadwaita is unsupported. Please use AdwStyleManager:color-scheme instead.

In Yum Extender:
Uncaught exception

Traceback (most recent call last):
File "/usr/lib/python3.12/site-packages/yumex/main.py", line 132, in do_command_line
setup_logging(debug=self.args.debug)
File "/usr/lib/python3.12/site-packages/yumex/utils/init.py", line 41, in setup_logging
file_handler = logging.handlers.RotatingFileHandler(log_file, backupCount=5)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib64/python3.12/logging/handlers.py", line 155, in init
BaseRotatingHandler.init(self, filename, mode, encoding=encoding,
File "/usr/lib64/python3.12/logging/handlers.py", line 58, in init
logging.FileHandler.init(self, filename, mode=mode,
File "/usr/lib64/python3.12/logging/init.py", line 1231, in init
StreamHandler.init(self, self._open())
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib64/python3.12/logging/init.py", line 1263, in _open
return open_func(self.baseFilename, self.mode,
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/stefanw/.local/share/yumex/yumex_debug.log'

**Comment by timlau** [comment]
FileNotFoundError: [Errno 2] No such file or directory: '/home/.../.local/share/yumex/yumex_debug.log'

is fixed in #115

**Comment by timlau** [comment]
Ctrl-A works fine when showing updates (Alt-U)

But if you search for something and press Ctrl-A, then the search string is selected, not the shown packages.

![Image](https://github.com/user-attachments/assets/11e7bbbb-de32-443c-9c8a-c502472e44f8)

**Comment by SinyoMinyo** [comment]
Thank you so much! Its actually fixed! I just tested it. (:
