### ISSUE TITLE
crash when updating flatpaks installed in system context

### ISSUE THREAD

**Issue by timlau** [timlau/yumex-ng#28]
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib64/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.11/site-packages/yumex/utils/__init__.py", line 124, in target
    result = self.task_func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yumex/backend/flatpak/backend.py", line 202, in do_update_all
    return self._do_transaction(
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yumex/backend/flatpak/backend.py", line 159, in _do_transaction
    refs = self._build_transaction(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yumex/backend/flatpak/backend.py", line 127, in _build_transaction
    refs = [(oper.get_ref(), action, oper.get_remote()) for oper in result]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not iterable

**Comment by timlau** [comment]
output from running "yumex -d" in a terminal

[log.txt](https://github.com/timlau/yumex-ng/files/11068235/log.txt)

**Comment by timlau** [comment]
### workaround
update the system flatpaks in a terminal
```
sudo flatpak -update --system
```
