### ISSUE TITLE
Uncaught exception: No module named 'dasbus'

### ISSUE THREAD

**Issue by edpil02** [timlau/yumex-ng#32]
I wanted  to try  yumex but get a issue when applying  queue changes :

 10:52:59 CRITICAL: (yumex) -  Uncaught exception: No module named 'dasbus'
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/yumex/ui/window.py", line 392, in on_actions
    self.on_apply_actions_clicked()
  File "/usr/lib/python3.11/site-packages/yumex/ui/window.py", line 290, in on_apply_actions_clicked
    done = self._do_transaction(queued)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yumex/ui/window.py", line 172, in _do_transaction
    with self.presenter.package_root_backend as root_backend:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yumex/backend/presenter.py", line 76, in package_root_backend
    self.dnf_backend_factory.get_root_backend()
  File "/usr/lib/python3.11/site-packages/yumex/backend/dnf/factory.py", line 22, in get_root_backend
    return self.get_dnf5_root_backend()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yumex/backend/dnf/factory.py", line 42, in get_dnf5_root_backend
    from yumex.backend.dnf5daemon import YumexRootBackend
  File "/usr/lib/python3.11/site-packages/yumex/backend/dnf5daemon/__init__.py", line 9, in <module>
    from .client import Dnf5DbusClient, gv_list
  File "/usr/lib/python3.11/site-packages/yumex/backend/dnf5daemon/client.py", line 5, in <module>
    from dasbus.connection import SystemMessageBus
ModuleNotFoundError: No module named 'dasbus'

Installed packages :
dnf5daemon-client.x86_64                                                       5.0.11-3.fc39                                   @rawhide
dnf5daemon-server.x86_64                                                       5.0.11-3.fc39                                   @rawhide
libdnf5.x86_64                                                                 5.0.11-3.fc39                                   @rawhide
libdnf5-cli.x86_64                                                             5.0.11-3.fc39                                   @rawhide
python3-libdnf5.x86_64

**Comment by edpil02** [comment]
Solve.
python-dasbus package is missing.
I had never heard of it only know  python-dbus...

Thanks for your job.

**Comment by timlau** [comment]
Thanks for reporting.

python3-dasbus is a more modern python dbus library, makes it much easier to work with dbus
https://dasbus.readthedocs.io/en/latest/

I forgot to add the python3-dasbus requirement to the spec file, fixed now, new copr packages is build now

https://copr.fedorainfracloud.org/coprs/timlau/yumex-ng/build/5993336/
