### ISSUE TITLE
Possible dnf5  api  change

### ISSUE THREAD

**Issue by edpil02** [timlau/yumex-ng#37]
I  made a try  with  latest dnf5  (5.0.14) and api seems to  have changed.

Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/yumex/ui/window.py", line 380, in on_actions
    self.on_apply_actions_clicked()
  File "/usr/lib/python3.11/site-packages/yumex/ui/window.py", line 278, in on_apply_actions_clicked
    done = self._do_transaction(queued)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yumex/ui/window.py", line 174, in _do_transaction
    result: TransactionResult = root_backend.build_transaction(queued)
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yumex/backend/dnf5daemon/__init__.py", line 160, in build_transaction
    return TransactionResult(True, data=self.build_result(content))
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yumex/backend/dnf5daemon/__init__.py", line 111, in build_result
    size = pkg["package_size"].get_uint64()
           ~~~^^^^^^^^^^^^^^^^
KeyError: 'package_size'

**Comment by timlau** [comment]
No API changes i documented in the DNF5 doc.
Added a more safe way to get the size. 
https://copr.fedorainfracloud.org/coprs/timlau/yumex-ng/build/6098303/

**Comment by edpil02** [comment]
I just tried it, the issue is resolved.
Thanks again.
