### ISSUE TITLE
flatpak error when searching for flatpaks: Remote "xxxx" not found

### ISSUE THREAD

**Issue by GloriousEggroll** [timlau/yumex-ng#39]
On my system I have flathub's repo enabled. In gnome software I can search for gimp and choose between fedora's flatpak repo or flathub, or fedora's standard package repo

On yumex-ng, I go to the flatpaks tab, click the + icon, change the dropdown from user to system, then select either fedora or flathub, and search 'gimp' and it errors:

```
17:57:52 CRITICAL: (yumex) -  Uncaught exception: flatpak-error-quark: Remote "fedora" not found (7)
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/yumex/ui/flatpak_installer.py", line 163, in on_search
    self._set_icon(fp_id, remote_name)
  File "/usr/lib/python3.11/site-packages/yumex/ui/flatpak_installer.py", line 126, in _set_icon
    icon_path = self.backend.get_icon_path(remote_name)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yumex/backend/flatpak/backend.py", line 72, in get_icon_path
    remote = self.user.get_remote_by_name(remote_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
gi.repository.GLib.GError: flatpak-error-quark: Remote "fedora" not found (7)
17:57:52 DEBUG : (yumex) -  traceback written to /home/tcrider/.local/share/yumex/traceback.txt
```
![Screenshot from 2023-06-23 18-02-21](https://github.com/timlau/yumex-ng/assets/11287837/8d4e7816-d61d-48bf-8359-e525a272dfa5)

**Comment by GloriousEggroll** [comment]
Found the problem:
```
File "/usr/lib/python3.11/site-packages/yumex/backend/flatpak/backend.py", line 72, in get_icon_path
    remote = self.user.get_remote_by_name(remote_name)
```

it's hardcoded to use self.user, thus the 'system' choice from the dropdown gets ignored. the repos defined are for system, so it cant find them when it tries to search the user's repositories for the 'fedora' "system" repository

if i change the code to self.system it performs the search correctly. there needs to be a switch there to determine if user or system is chosen from the dropdown

**Comment by GloriousEggroll** [comment]
I have a fix for this, will open a PR, however i also found another bug related to the dropdowns, will open a new issue for it

**Comment by timlau** [comment]
Thanks for reporting, I will look into this issue

**Comment by GloriousEggroll** [comment]
Figure it might save some time if I just post the patch before forking + opening PR, my method is probably a bit hacky with if/else statements, not sure if you want to do it a more efficient way:
```
diff --git a/yumex/backend/flatpak/backend.py b/yumex/backend/flatpak/backend.py
index 913eb19..0c12346 100644
--- a/yumex/backend/flatpak/backend.py
+++ b/yumex/backend/flatpak/backend.py
@@ -53,9 +53,12 @@ class FlatpakBackend:
                     found.append(ref.get_name())
         return found
 
-    def find_ref(self, source: str, key: str) -> str | None:
+    def find_ref(self, source: str, key: str, location: FlatpakLocation) -> str | None:
         """find the ref string containing a key"""
-        refs: list[FlatpakRef] = self.user.list_remote_refs_sync(source)
+        if location == "system":
+            refs: list[FlatpakRef] = self.system.list_remote_refs_sync(source)
+        else:
+            refs: list[FlatpakRef] = self.user.list_remote_refs_sync(source)
         found = None
         for ref in refs:
             if ref.get_kind() == Flatpak.RefKind.APP:
@@ -67,9 +70,12 @@ class FlatpakBackend:
             return ref
         return None
 
-    def get_icon_path(self, remote_name: str) -> str | None:
+    def get_icon_path(self, remote_name: str, location: FlatpakLocation) -> str | None:
         """get the path to flatpak icon cache"""
-        remote = self.user.get_remote_by_name(remote_name)
+        if location == "system":
+            remote = self.system.get_remote_by_name(remote_name)
+        else:
+            remote = self.user.get_remote_by_name(remote_name)
         if remote:
             appstream_dir = remote.get_appstream_dir().get_path()
             return f"{appstream_dir}/icons/flatpak/128x128/"
diff --git a/yumex/ui/flatpak_installer.py b/yumex/ui/flatpak_installer.py
index 706929f..d508765 100644
--- a/yumex/ui/flatpak_installer.py
+++ b/yumex/ui/flatpak_installer.py
@@ -123,7 +123,8 @@ class YumexFlatpakInstaller(Adw.Window):
         if not remote_name:
             self.icon.set_from_icon_name("flatpak-symbolic")
             return
-        icon_path = self.backend.get_icon_path(remote_name)
+        location = FlatpakLocation(self.location.get_selected_item().get_string())
+        icon_path = self.backend.get_icon_path(remote_name, location)
         icon_file = Path(f"{icon_path}/{id}.png")
         if icon_file.exists():
             self.icon.set_from_file(icon_file.as_posix())
diff --git a/yumex/ui/flatpak_view.py b/yumex/ui/flatpak_view.py
index bce5629..a8118ae 100644
--- a/yumex/ui/flatpak_view.py
+++ b/yumex/ui/flatpak_view.py
@@ -98,7 +98,7 @@ class YumexFlatpakView(Gtk.ListView):
         if fp_id:
             remote = flatpak_installer.remote.get_selected_item().get_string()
             location = flatpak_installer.location.get_selected_item().get_string()
-            ref = self.backend.find_ref(remote, fp_id)
+            ref = self.backend.find_ref(remote, fp_id, location)
             log(
                 f"FlatPakView.install : remote: {remote} location: {location} ref: {ref}"
             )
```

**Comment by timlau** [comment]
Look fine, instead of 
`if location == "system":` 
in find_ref

Do it like in find

https://github.com/timlau/yumex-ng/blob/16b8221720eba0ea44a93a074129d0f60fdcf21b/yumex/backend/flatpak/backend.py#L50

**Comment by GloriousEggroll** [comment]
done and done
https://github.com/timlau/yumex-ng/pull/41/files
