### ISSUE TITLE
dasbus.error.DBusError: rpm transaction failed with code 5.

### ISSUE THREAD

**Issue by timlau** [timlau/yumex-ng#46]
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/dasbus/client/handler.py", line 95, in _async_call_finish
    callback(
  File "/usr/lib/python3.11/site-packages/dasbus/client/handler.py", line 465, in _method_callback
    callback(
  File "/usr/lib/python3.11/site-packages/yumex/backend/dnf5daemon/client.py", line 37, in callback
    self.res = call()
               ^^^^^^
  File "/usr/lib/python3.11/site-packages/dasbus/client/handler.py", line 466, in <lambda>
    lambda: self._get_method_reply(getter),
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/dasbus/client/handler.py", line 483, in _get_method_reply
    return self._handle_method_error(error)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/dasbus/client/handler.py", line 509, in _handle_method_error
    raise exception from None
dasbus.error.DBusError: rpm transaction failed with code 5.

**Comment by timlau** [comment]
Think it is ok now, have not seen any issues for a long time
