### ISSUE TITLE
Yumex crash when repo doesn't provide "Update info -> Advisory Type"

### ISSUE THREAD

**Issue by L-U-T-i** [timlau/yumex-ng#49]
In my build (for Rocky Linux 9, a bit adjusted code due to that), if I select "Update info" instead of default "Description" and select a package for which "Advisory Type" is not provided by repo (as EPEL packages for instance), yumex-ng crash with:
```
18:13:36 DEBUG : (yumex) -  << Completed async job : get_package_info.
18:13:36 CRITICAL: (yumex) -  Uncaught exception: 4
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/yumex_ng/ui/window.py", line 226, in completed
    self.package_info.update(self.info_type, pkg_info)
  File "/usr/lib/python3.9/site-packages/yumex_ng/ui/package_info.py", line 66, in update
    self.write_update(info)
  File "/usr/lib/python3.9/site-packages/yumex_ng/ui/package_info.py", line 84, in write_update
    self.add_update_info(info)
  File "/usr/lib/python3.9/site-packages/yumex_ng/ui/package_info.py", line 98, in add_update_info
    upd_type = ADVISORY_TYPES[pkg_info["type"]]
KeyError: 4
```
I've fixed that with:
```
diff -up a/yumex/ui/package_info.py b/yumex/ui/package_info.py
--- a/yumex/ui/package_info.py	2023-12-12 18:09:21.000000000 +0100
+++ b/yumex/ui/package_info.py	2023-12-12 18:37:16.950469268 +0100
@@ -95,7 +95,10 @@ class YumexPackageInfo(Gtk.Box):
     def add_update_info(self, pkg_info):
         release = pkg_info["id"]
         self.release.set_label(release)
-        upd_type = ADVISORY_TYPES[pkg_info["type"]]
+        try:
+            upd_type = ADVISORY_TYPES[pkg_info["type"]]
+        except:
+            upd_type = _("Information not available")
         self.type.set_label(upd_type)
         issued = pkg_info["updated"]
         self.issued.set_label(issued)

```

As said, it might be just due to my particular build (code adjustments), but looking at the code, I am not sure...

**Comment by timlau** [comment]
I have created a fix, to have a default value for undefined pkg_info['type'] values.
Test it out and let me know if it works.

**Comment by L-U-T-i** [comment]
It works, thank you.

**Comment by timlau** [comment]
Fine
