### ISSUE TITLE
yumex 5.0.0: AttributeError: 'list' object has no attribute 'get_size'

### ISSUE THREAD

**Issue by AngryPenguinPL** [timlau/yumex-ng#74]
When try search flatpak I see this error:

`
20:52:46 CRITICAL: (yumex) -  Uncaught exception: 'list' object has no attribute 'get_size'
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/yumex/ui/window.py", line 383, in on_actions
    self.flatpak_view.search()
  File "/usr/lib/python3.11/site-packages/yumex/ui/flatpak_view.py", line 99, in search
    flatpak_search = YumexFlatpakSearch(self.presenter)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yumex/ui/flatpak_search.py", line 60, in __init__
    self.setup_location()
  File "/usr/lib/python3.11/site-packages/yumex/ui/flatpak_search.py", line 79, in setup_location
    self.on_location_selected()
  File "/usr/lib/python3.11/site-packages/yumex/ui/flatpak_search.py", line 86, in on_location_selected
    self.app_search.add_installation(self.backend.get_installation(fp_location))
  File "/usr/lib/python3.11/site-packages/yumex/backend/flatpak/search.py", line 92, in add_installation
    self.add_remote(remote, inst)
  File "/usr/lib/python3.11/site-packages/yumex/backend/flatpak/search.py", line 99, in add_remote
    self.remotes[remote_name] = self._load_appstream_metadata(remote)
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yumex/backend/flatpak/search.py", line 111, in _load_appstream_metadata
    for i in range(components.get_size()):
                   ^^^^^^^^^^^^^^^^^^^
AttributeError: 'list' object has no attribute 'get_size'
20:52:46 DEBUG : (yumex) -  traceback written to /home/x/.local/share/yumex/traceback_06-14-2024_205246.txt
`

Like on screenshot
![Zrzut ekranu z 2024-06-14 20-53-04](https://github.com/timlau/yumex-ng/assets/3121142/6d97dcdb-d012-40ad-bb77-54c3c281cdef)

Details:
OpenMandriva Cooker
Flatpak 1.15.8
Compiler Clang 18.1.7

**Comment by timlau** [comment]
looks strange, what version of the appstream package are you running
https://github.com/ximion/appstream

**Comment by AngryPenguinPL** [comment]
In time I built and ran it I had appstream 0.16.4 in my system.

Now I made testing update to appststream 1.0.3 (latest). Installed that in system and also to make sure new one is used forced build yumex with 1.0.3 in tree. I even also rebuild flatpak with appstream 1.0.3.

Now there is still error but a bit different:
```
17:17:01 WARNING: (py.warnings) -  /usr/lib/python3.11/site-packages/yumex/backend/flatpak/search.py:104: Warning: g_object_new_with_properties: assertion 'G_TYPE_IS_OBJECT (object_type)' failed
  metadata = AppStream.Metadata.new()

17:17:01 CRITICAL: (yumex) -  Uncaught exception: constructor returned NULL
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/yumex/ui/window.py", line 383, in on_actions
    self.flatpak_view.search()
  File "/usr/lib/python3.11/site-packages/yumex/ui/flatpak_view.py", line 99, in search
    flatpak_search = YumexFlatpakSearch(self.presenter)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yumex/ui/flatpak_search.py", line 60, in __init__
    self.setup_location()
  File "/usr/lib/python3.11/site-packages/yumex/ui/flatpak_search.py", line 79, in setup_location
    self.on_location_selected()
  File "/usr/lib/python3.11/site-packages/yumex/ui/flatpak_search.py", line 86, in on_location_selected
    self.app_search.add_installation(self.backend.get_installation(fp_location))
  File "/usr/lib/python3.11/site-packages/yumex/backend/flatpak/search.py", line 92, in add_installation
    self.add_remote(remote, inst)
  File "/usr/lib/python3.11/site-packages/yumex/backend/flatpak/search.py", line 99, in add_remote
    self.remotes[remote_name] = self._load_appstream_metadata(remote)
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/yumex/backend/flatpak/search.py", line 104, in _load_appstream_metadata
    metadata = AppStream.Metadata.new()
               ^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: constructor returned NULL
```
![obraz](https://github.com/timlau/yumex-ng/assets/3121142/ccdf949d-b77b-4c02-ad7e-138a1e25a184)

**Comment by timlau** [comment]
Look like your AppStrem is broken, I use 1.0.2 on fedora 40
```
rpm -qi appstream
Name        : appstream
Version     : 1.0.2
Release     : 2.fc40
Architecture: x86_64
Install Date: tir 23 apr 2024 16:52:17 CEST
Group       : Unspecified
Size        : 3678623
License     : GPL-2.0-or-later AND LGPL-2.1-or-later
Signature   : RSA/SHA256, søn 10 mar 2024 00:10:19 CET, Key ID 0727707ea15b79cc
Source RPM  : appstream-1.0.2-2.fc40.src.rpm
Build Date  : lør 09 mar 2024 22:48:12 CET
Build Host  : buildhw-x86-02.iad2.fedoraproject.org
Packager    : Fedora Project
Vendor      : Fedora Project
URL         : https://github.com/ximion/appstream
Bug URL     : https://bugz.fedoraproject.org/appstream
Summary     : Utilities to generate, maintain and access the AppStream database
Description :
AppStream makes it easy to access application information from the
AppStream database over a nice GObject-based interface.
```

**Comment by timlau** [comment]
you can test with this simple code, it should run without problems
```
import gi
gi.require_version("AppStream", "1.0")
from gi.repository import AppStream
metadata = AppStream.Metadata.new()
```

**Comment by timlau** [comment]
check your python3-gobject version also, it contains the basic gi.repository stuff
```
rpm -qi python3-gobject-base
Name        : python3-gobject-base
Version     : 3.48.2
Release     : 1.fc40
Architecture: x86_64
Install Date: tir 23 apr 2024 16:52:10 CEST
Group       : Unspecified
Size        : 1479221
License     : LGPL-2.1-or-later
Signature   : RSA/SHA256, lør 06 apr 2024 14:48:55 CEST, Key ID 0727707ea15b79cc
Source RPM  : pygobject3-3.48.2-1.fc40.src.rpm
Build Date  : lør 06 apr 2024 13:20:41 CEST
Build Host  : buildvm-x86-05.iad2.fedoraproject.org
Packager    : Fedora Project
Vendor      : Fedora Project
URL         : https://wiki.gnome.org/Projects/PyGObject
Bug URL     : https://bugz.fedoraproject.org/pygobject3
Summary     : Python 3 bindings for GObject Introspection base package
Description :
This package provides the non-cairo specific bits of the GObject Introspection
library.
```

**Comment by AngryPenguinPL** [comment]
```
rpm -qi appstream
Name        : appstream
Version     : 1.0.3
Release     : 1
DistTag     : omv2490
Architecture: x86_64
Install Date: sob, 15 cze 2024, 15:00:43
Group       : System/Configuration/Packaging
Size        : 2908664
License     : GPLv2+ and LGPLv2.1+
Signature   : (none)
Source RPM  : appstream-1.0.3-1.src.rpm
Build Date  : sob, 15 cze 2024, 14:55:32
Build Host  : ph18-4.openmandriva.org
Packager    : angrypenguin <angrypenguinpoland@gmail.com>
Vendor      : OpenMandriva
URL         : https://www.freedesktop.org/wiki/Distributions/AppStream/Software
Bug URL     : https://issues.openmandriva.org
Summary     : Utilities to generate, maintain and access the AppStream Xapian database
Description :
AppStream-Core makes it easy to access application information from the
AppStream database over a nice GObject-based interface.
```

```
rpm -qi python-gobject3
Name        : python-gobject3
Version     : 3.48.2
Release     : 1
DistTag     : omv2490
Architecture: x86_64
Install Date: pon, 15 kwi 2024, 16:09:43
Group       : Development/Python
Size        : 120443
License     : LGPLv2+ and MIT
Signature   : RSA/SHA256, wto, 9 kwi 2024, 19:50:25, Key ID 180922d8bf81de15
Source RPM  : python-gobject3-3.48.2-1.src.rpm
Build Date  : wto, 9 kwi 2024, 19:47:04
Build Host  : ryzen9-4.openmandriva.org
Packager    : angrypenguin <angrypenguinpoland@gmail.com>
Vendor      : OpenMandriva
URL         : https://www.gnome.org
Bug URL     : https://issues.openmandriva.org
Summary     : Python bindings for GObject Introspection
Description :
The python-gobject3 package provides a convenient wrapper for the GObject
library for use in Python programs.
```

**Comment by AngryPenguinPL** [comment]
After small cleaning and recompiling appstream problem gone.
Thanks.
